"""ronda en marcas

Revision ID: 14371d3093da
Revises: e4f3c3c384e5
Create Date: 2026-05-17 21:55:31.667294

"""
from alembic import op
import sqlalchemy as sa


revision = '14371d3093da'
down_revision = 'e4f3c3c384e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marcas', sa.Column('ronda', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marcas', 'ronda')
    # ### end Alembic commands ###