"""tabla usuarios

Revision ID: 66c3f1f37b0a
Revises: 14371d3093da
Create Date: 2026-05-18 17:19:31.516542

"""
from alembic import op
import sqlalchemy as sa


revision = '66c3f1f37b0a'
down_revision = '14371d3093da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###