"""tabla usuarios v2

Revision ID: 9d0bd5a10a01
Revises: f870554e7407
Create Date: 2026-05-18 17:24:15.150986

"""
from alembic import op
import sqlalchemy as sa


revision = '9d0bd5a10a01'
down_revision = 'f870554e7407'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###