"""tablas iniciales completas

Revision ID: d703d93962b7
Revises: 
Create Date: 2026-05-17 16:48:58.338491

"""
from alembic import op
import sqlalchemy as sa


revision = 'd703d93962b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('nivel', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_table('competencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('lugar', sa.String(length=200), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('organizacion', sa.String(length=20), nullable=True),
    sa.Column('subtipo', sa.String(length=30), nullable=True),
    sa.Column('nivel', sa.String(length=20), nullable=True),
    sa.Column('escenario', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencias_id'), 'competencias', ['id'], unique=False)
    op.create_table('pruebas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('unidad', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pruebas_id'), 'pruebas', ['id'], unique=False)
    op.create_table('atletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('colegio', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atletas_id'), 'atletas', ['id'], unique=False)
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('prueba_id', sa.Integer(), nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.Float(), nullable=False),
    sa.Column('es_pb', sa.Boolean(), nullable=True),
    sa.Column('posicion', sa.Integer(), nullable=True),
    sa.Column('viento', sa.Float(), nullable=True),
    sa.Column('homologada', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atletas.id'], ),
    sa.ForeignKeyConstraint(['competencia_id'], ['competencias.id'], ),
    sa.ForeignKeyConstraint(['prueba_id'], ['pruebas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_id'), 'marcas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marcas_id'), table_name='marcas')
    op.drop_table('marcas')
    op.drop_index(op.f('ix_atletas_id'), table_name='atletas')
    op.drop_table('atletas')
    op.drop_index(op.f('ix_pruebas_id'), table_name='pruebas')
    op.drop_table('pruebas')
    op.drop_index(op.f('ix_competencias_id'), table_name='competencias')
    op.drop_table('competencias')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_table('clubs')
    # ### end Alembic commands ###