"""entrenadores y entrenador atleta

Revision ID: e264a6f5f0bc
Revises: 9d0bd5a10a01
Create Date: 2026-07-08 23:08:28.164016

"""
from alembic import op
import sqlalchemy as sa


revision = 'e264a6f5f0bc'
down_revision = '9d0bd5a10a01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrenadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_entrenadores_id'), 'entrenadores', ['id'], unique=False)
    op.create_table('entrenador_atleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atletas.id'], ),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrenador_atleta_id'), 'entrenador_atleta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entrenador_atleta_id'), table_name='entrenador_atleta')
    op.drop_table('entrenador_atleta')
    op.drop_index(op.f('ix_entrenadores_id'), table_name='entrenadores')
    op.drop_table('entrenadores')
    # ### end Alembic commands ###