"""fecha inicio fin en competencias

Revision ID: e4f3c3c384e5
Revises: d703d93962b7
Create Date: 2026-05-17 19:54:15.026722

"""
from alembic import op
import sqlalchemy as sa


revision = 'e4f3c3c384e5'
down_revision = 'd703d93962b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competencias', sa.Column('fecha_inicio', sa.Date(), nullable=False))
    op.add_column('competencias', sa.Column('fecha_fin', sa.Date(), nullable=False))
    op.drop_column('competencias', 'fecha')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competencias', sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('competencias', 'fecha_fin')
    op.drop_column('competencias', 'fecha_inicio')
    # ### end Alembic commands ###