"""tabla usuarios

Revision ID: f870554e7407
Revises: 66c3f1f37b0a
Create Date: 2026-05-18 17:21:12.279847

"""
from alembic import op
import sqlalchemy as sa


revision = 'f870554e7407'
down_revision = '66c3f1f37b0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###